### ISSUE TITLE
adding support for  "Get Batch Last Reading"

### ISSUE THREAD

**Issue by andreypopov** [enorfelt/node-red-contrib-brewfather#1]
please!)

**Comment by enorfelt** [comment]
Looks like some new endpoints. Will have a look thx 😊

**Comment by andreypopov** [comment]
![2020-12-21_16-35-32](https://user-images.githubusercontent.com/1624839/102782532-90eec300-43aa-11eb-872b-42c4785c7e46.png)

it gives fresh data for devices

**Comment by enorfelt** [comment]
@andreypopov 1.2.0 is now released with a fix for this issue

**Comment by andreypopov** [comment]
thanks, works fine!
