### ISSUE TITLE
msg.payload_in

### ISSUE THREAD

**Issue by andreypopov** [enorfelt/node-red-contrib-brewfather#2]
please, save payload (incoming data) as payload_in, so we will not lose it )

![2020-12-21_16-45-32](https://user-images.githubusercontent.com/1624839/102783436-fc856000-43ab-11eb-98af-baaec7280c52.png)

**Comment by enorfelt** [comment]
@andreypopov 1.2.0 is now released with a fix for this issue

I choosed msg.payloadIn as for me its more of a standard for JSON
