### ISSUE TITLE
Can't use nested property for parameter input

### ISSUE THREAD

**Issue by toddq** [enorfelt/node-red-contrib-brewfather#5]
I'm trying to get the list of fermenting batches, run that through the 'split' node, then for each batch get the batches last reading.  Spent hours trying to figure out why the result was only "not found", which my best guess was that the batch id wasn't getting set in the input correctly.  I was using `msg.payload._id`, which should've been correct.  It appears that the `msg.` input can only be the name of a single direct-child property though, that it's not supporting evaluating more deeply nested properties.  I just figured out that if I run it through a 'change' node and make a copy of `msg.payload._id` to `msg.batch_id`, I can then use that.

I think I've narrowed the issue down to most likely this line - https://github.com/enorfelt/node-red-contrib-brewfather/blob/240993064a901d82a06a6a1a3b8f3e7d25ce1c01/brewfather-api-request.js#L27.  I'm not familiar enough with this however to offer a PR.

**Comment by enorfelt** [comment]
@toddq should be fixed and release in v2.0.0 now. This also brings full support for BF API version 2
